version: "3"

services:
  postgres:
    image: postgres:12.3
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data
  sonarqube:
    image: sonarqube:7.7-community
    ports:
      - "9000:9000"
    environment:
      - sonar.jdbc.url=jdbc:postgresql://postgres:5432/sonar
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
